name: Azure Web App - FastAPI ML Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # ⬇️ DO NOT ZIP or VENV! Deploy source directory only
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: shipmentdelivery
          package: .
